### ISSUE TITLE
feat: add foundry framework (hybrid project)

### ISSUE THREAD

**Issue by luislucena16** [blockful-io/swaplace-contracts#138]
the objective and what it allows is:
- add foundry without removing hardhat, this to give flexibility and more focus to the tests.
- it gives more facility for the tests since they are in solidity and not JS or TS.
- allows to create deeper tests
- it gives you the facility to continue using hardhat, you can test in both frameworks and then decide whether to migrate to another ;)

**Comment by 0xneves** [comment]
We debated this a lot and honestly I rather it would be in Foundry, but since the purpose of Swaplace is not to dive too deep but rather find a solid state that everyone can read. People still kinda freak out with Rust 😄 

Foundry is the next-level tool while Hardhat is more widely known, it's kinda easy for newcomers.

We are wrapping up the Chain Link Hackathon and will deliver the Swaplace+CCIP using Foundry.

**Comment by luislucena16** [comment]
I agree with your criteria, that's why I mentioned using a hybrid model, since there is a library that provides the facility and there are no problems. Maybe some will contribute in foundry and others in hardhat

**Comment by 0xneves** [comment]
We are using Echidna for the Fuzz and I think it covers the Foundry for this simple case. I'm closing this for now. It will resurrect in the future, I'm pretty sure.
