### ISSUE TITLE
feat: add `onlyOwner` modifier and library

### ISSUE THREAD

**Issue by luislucena16** [blockful-io/swaplace-contracts#161]
- the goal is to add the `onlyOwner` modifier with the `Ownable` library directly into the function, ie:

remove this:

```
if (swap.owner != msg.sender) revert InvalidAddress(msg.sender);
```

using this:

```
function createSwap(
        Swap calldata swap
    ) public onlyOwner returns (uint256) {}
```

and improve the logic of the owner related function!

@0xneves please assign this to me!

**Comment by 0xneves** [comment]
@luislucena16 

The onlyOwner modifier is standard when dealing with ownership over contracts. Although Swaplace is not meant to have owners or Ownership features.

The `swap.owner` exists because swaps can be built by anyone, but can only be created if the owner proves to be msg.sender. 

Whereas using OnlyOwner is not meant to verify `swap.owner`, it would be better with a modifier such as `OnlySender(swap.owner)`. Although this would create more complexity for legibility, and require more gas.

Closing this issue because it does not improve the overall contract.

**Comment by luislucena16** [comment]
I understand! the owner's approach is different from what I thought, thanks for the clarification!
